"""Add ondelete='CASCADE' to user_id foreign key

Revision ID: a03f9ca66ed0
Revises: 
Create Date: 2023-11-25 19:15:17.521321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03f9ca66ed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_item_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_cart_item_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_item_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_cart_item_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###

